name: Deploy React to Pages
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Build
        run: |
          cd werewolf-app
          npm install
          npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './werewolf-app/dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4